import {initializeApp} from "https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js";
import {getAuth,onAuthStateChanged,createUserWithEmailAndPassword,signInWithEmailAndPassword,sendPasswordResetEmail,signOut,setPersistence,browserLocalPersistence,updateProfile} from "https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js";
import {getFirestore,doc,getDoc,getDocs,setDoc,addDoc,updateDoc,collection,query,where,limit,orderBy,onSnapshot,serverTimestamp,arrayUnion,runTransaction} from "https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js";
import {getStorage,ref,uploadBytes,getDownloadURL} from "https://www.gstatic.com/firebasejs/10.12.2/firebase-storage.js";

const firebaseConfig={apiKey:"AIzaSyCpRK0HE1z7iQ00WaBVbABh-RIjkqz38k8",authDomain:"qavli-37983.firebaseapp.com",projectId:"qavli-37983",storageBucket:"qavli-37983.firebasestorage.app",appId:"1:168938701514:web:783d81a63d8e4423e56a33",messagingSenderId:"168938701514"};
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),storage=getStorage(app);
const $=id=>document.getElementById(id);
const state={user:null,profile:null,chats:[],active:null,messages:[],unsubs:[],search:"",chatSearch:"",reply:null,theme:localStorage.getItem("qavli-theme")||"light"};
const profileCache=new Map();
let toastTimer=0,typingTimeout=0;

function toast(msg){const t=$("toast");t.textContent=msg;t.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove("show"),2600)}
function initials(name){return String(name||"Q").trim().slice(0,1).toUpperCase()||"Q"}
function errText(e){const c=e?.code||"";const map={"auth/invalid-credential":"Email or password is incorrect.","auth/invalid-email":"Please enter a valid email.","auth/user-not-found":"Account not found.","auth/wrong-password":"Email or password is incorrect.","auth/email-already-in-use":"This email is already registered.","auth/weak-password":"Password must be at least 6 characters.","auth/network-request-failed":"Network problem. Check your connection.","permission-denied":"Firebase rules denied this action.","failed-precondition":"Firebase needs an index or configuration update.","unavailable":"Firebase is temporarily unavailable."};return map[c]||e?.message||"Something went wrong."}
function screen(name){document.querySelectorAll(".screen").forEach(x=>x.classList.remove("active"));$(name).classList.add("active")}
function setBusy(btn,busy,label){btn.disabled=busy;if(busy){btn.dataset.old=btn.textContent;btn.textContent=label||"Please wait…"}else if(btn.dataset.old){btn.textContent=btn.dataset.old}}
function clearAllListeners(){state.unsubs.forEach(fn=>{try{fn()}catch{}});state.unsubs=[]}
function clearChatListeners(){while(state.unsubs.length>1){const fn=state.unsubs.pop();try{fn()}catch{}}}
function showAuth(mode="signin"){$("authTitle").textContent=mode==="signup"?"Create your QAVLI account":"Welcome back";$("authSub").textContent=mode==="signup"?"Create your account using the existing QAVLI Firebase service.":"Sign in to continue to your private conversations.";$("authAction").textContent=mode==="signup"?"Create account":"Sign in";$("authSwitch").textContent=mode==="signup"?"Already have an account? Sign in":"New to QAVLI? Create account";$("authForm").dataset.mode=mode;screen("auth");$("email").focus()}
function showSetup(){screen("setup");$("username").focus()}
function showHome(){screen("home");renderChats()}
function showChat(){screen("chat");document.querySelector("#chat .app-shell").classList.add("chat-open")}
function closeChat(){clearChatListeners();state.active=null;state.messages=[];document.querySelector("#chat .app-shell").classList.remove("chat-open");showHome()}
function avatarHTML(profile,name){const src=profile?.avatarUrl;if(src)return '<div class="avatar"><img src="'+src.replace(/"/g,"&quot;")+'" alt=""></div>';return '<div class="avatar">'+initials(name)+"</div>"}
async function loadProfile(user){const snap=await getDoc(doc(db,"users",user.uid));return snap.exists()?{id:snap.id,...snap.data()}:null}
async function getUserProfile(uid){if(!uid)return null;if(profileCache.has(uid))return profileCache.get(uid);try{const snap=await getDoc(doc(db,"users",uid));const p=snap.exists()?{id:snap.id,...snap.data()}:null;if(p)profileCache.set(uid,p);return p}catch{return null}}
async function hydrateChat(c){if(c.isGroup)return c;const other=(c.members||[]).find(x=>x!==state.user?.uid);if(!other)return c;const cached=profileCache.get(other);if(cached){c.memberNames={...(c.memberNames||{}),[other]:cached.displayName||cached.username||"User"};c.memberAvatars={...(c.memberAvatars||{}),[other]:cached.avatarUrl||""};return c}const p=await getUserProfile(other);if(p){c.memberNames={...(c.memberNames||{}),[other]:p.displayName||p.username||"User"};c.memberAvatars={...(c.memberAvatars||{}),[other]:p.avatarUrl||""};}return c}
async function hydrateChatList(){const visible=state.chats.filter(c=>chatTitle(c).toLowerCase().includes(state.search.toLowerCase()));await Promise.all(visible.map(hydrateChat));renderChats();}
async function finishAuth(user){state.user=user;try{state.profile=await loadProfile(user);if(!state.profile){showSetup();return}await setDoc(doc(db,"users",user.uid),{online:true,lastSeen:serverTimestamp()},{merge:true});startHomeListener();showHome();}catch(e){showFatal("Your account signed in, but QAVLI could not load your profile. "+errText(e))}}
function showFatal(msg){screen("fatal");$("fatalText").textContent=msg}
async function signIn(){const email=$("email").value.trim(),pw=$("password").value;if(!email||!pw)return $("authError").textContent="Enter your email and password.";const b=$("authAction");$("authError").textContent="";setBusy(b,true,"Signing in…");try{await setPersistence(auth,browserLocalPersistence);await signInWithEmailAndPassword(auth,email,pw)}catch(e){$("authError").textContent=errText(e);setBusy(b,false)}}
async function signUp(){const email=$("email").value.trim(),pw=$("password").value;if(!email||!pw)return $("authError").textContent="Enter your email and password.";const b=$("authAction");$("authError").textContent="";setBusy(b,true,"Creating…");try{await setPersistence(auth,browserLocalPersistence);await createUserWithEmailAndPassword(auth,email,pw)}catch(e){$("authError").textContent=errText(e);setBusy(b,false)}}
async function saveProfile(){const u=$("username").value.trim().toLowerCase(),d=$("displayName").value.trim();if(!/^[a-z0-9_]{3,20}$/.test(u))return $("setupError").textContent="Username must be 3–20 characters: a-z, 0-9 or _.";if(!d||d.length>40)return $("setupError").textContent="Enter a display name up to 40 characters.";const b=$("saveProfile");$("setupError").textContent="";setBusy(b,true,"Saving…");try{const user=state.user;await runTransaction(db,async tx=>{const existing=await tx.get(doc(db,"usernames",u));if(existing.exists()&&existing.data().uid!==user.uid)throw new Error("USERNAME_TAKEN");tx.set(doc(db,"usernames",u),{uid:user.uid,createdAt:serverTimestamp()});tx.set(doc(db,"users",user.uid),{username:u,displayName:d,online:true,lastSeen:serverTimestamp()},{merge:true})});await updateProfile(user,{displayName:d});state.profile=await loadProfile(user);startHomeListener();showHome();toast("Profile ready.");}catch(e){$("setupError").textContent=e.message==="USERNAME_TAKEN"?"That username is already taken.":errText(e);setBusy(b,false)}}
async function resetPassword(){const email=$("email").value.trim();if(!email)return $("authError").textContent="Enter your email first.";try{await sendPasswordResetEmail(auth,email);toast("Password reset email sent.");}catch(e){$("authError").textContent=errText(e)}}

function startHomeListener(){clearAllListeners();const q=query(collection(db,"chats"),where("members","array-contains",state.user.uid),limit(80));const unsub=onSnapshot(q,snap=>{state.chats=snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(b.lastActivityAt?.toMillis?.()||0)-(a.lastActivityAt?.toMillis?.()||0));renderChats()},e=>{toast("Could not load chats: "+errText(e));renderChatsError(e)});state.unsubs=[unsub]}
function renderChatsError(e){$("chatList").innerHTML='<div class="empty-card" style="padding:25px"><b>Could not load conversations.</b><p>'+errText(e)+'</p></div>'}
function chatTitle(c){if(c.isGroup)return c.name||"Group";const other=(c.members||[]).find(x=>x!==state.user.uid);return c.memberNames?.[other]||c.names?.[other]||"Conversation"}
function chatProfile(c){if(c.isGroup)return{displayName:c.name||"Group"};const other=(c.members||[]).find(x=>x!==state.user.uid);return{displayName:c.memberNames?.[other]||"Conversation",avatarUrl:c.memberAvatars?.[other]||""}}
function renderChats(){const list=$("chatList"),needle=state.search.toLowerCase();list.innerHTML="";const arr=state.chats.filter(c=>chatTitle(c).toLowerCase().includes(needle));if(!arr.length){list.innerHTML='<div class="empty-card" style="padding:30px 10px;text-align:center"><b>No conversations yet</b><p>Use “New chat” to find someone by username.</p></div>';return}arr.forEach(c=>{const b=document.createElement("button");b.className="chat-row"+(state.active?.id===c.id?" selected":"");const p=chatProfile(c);b.innerHTML=avatarHTML(p,p.displayName)+'<div class="chat-copy"><strong></strong><small></small></div>';b.querySelector("strong").textContent=p.displayName;b.querySelector("small").textContent=c.lastMessage||"Start a conversation";b.onclick=()=>openChat(c);list.appendChild(b)});if(arr.some(c=>!c.isGroup&&(c.members||[]).some(x=>x!==state.user?.uid&&!profileCache.has(x))))hydrateChatList()}
function openModal(id){$(id).classList.add("open");$(id).querySelector("input")?.focus()}
function closeModal(){document.querySelectorAll(".modal-backdrop").forEach(x=>x.classList.remove("open"))}
async function newChat(){const u=($("newChatUser").value||"").trim().toLowerCase();$("newChatError").textContent="";if(!/^[a-z0-9_]{3,20}$/.test(u))return $("newChatError").textContent="Enter a valid username.";try{const qs=await getDocs(query(collection(db,"users"),where("username","==",u),limit(1)));if(qs.empty)return $("newChatError").textContent="User not found.";const other=qs.docs[0];if(other.id===state.user.uid)return $("newChatError").textContent="You cannot start a chat with yourself.";const existing=state.chats.find(c=>!c.isGroup&&c.members?.length===2&&c.members.includes(other.id));if(existing){closeModal();return openChat(existing)}const otherData=other.data(),names={[state.user.uid]:state.profile.displayName,[other.id]:otherData.displayName||u},avatars={[state.user.uid]:state.profile.avatarUrl||"",[other.id]:otherData.avatarUrl||""};const ref=await addDoc(collection(db,"chats"),{isGroup:false,members:[state.user.uid,other.id],memberNames:names,memberAvatars:avatars,createdBy:state.user.uid,lastActivityAt:serverTimestamp(),lastMessage:""});closeModal();$("newChatUser").value="";openChat({id:ref.id,isGroup:false,members:[state.user.uid,other.id],memberNames:names,memberAvatars:avatars,lastMessage:""})}catch(e){$("newChatError").textContent=errText(e)}}
async function createGroup(){const name=($("groupName").value||"").trim();if(!name||name.length>60)return $("groupError").textContent="Enter a group name up to 60 characters.";try{const ref=await addDoc(collection(db,"chats"),{isGroup:true,name,members:[state.user.uid],createdBy:state.user.uid,lastActivityAt:serverTimestamp(),lastMessage:""});closeModal();const c={id:ref.id,isGroup:true,name,members:[state.user.uid],createdBy:state.user.uid,lastMessage:""};state.chats=[c,...state.chats];openChat(c)}catch(e){$("groupError").textContent=errText(e)}}
async function openChat(c){clearChatListeners();state.active=c;state.messages=[];if(!c.isGroup){await hydrateChat(c)}showChat();$("chatName").textContent=chatTitle(c);$("chatStatus").textContent=c.isGroup?"Group conversation":"Private conversation";$("chatAvatar").innerHTML=avatarHTML(chatProfile(c),chatTitle(c));$("manageBtn").hidden=!c.isGroup||c.createdBy!==state.user.uid;$("inviteBtn").hidden=!c.isGroup;$("chatSearch").value="";state.chatSearch="";$("chatTools").classList.remove("open");$("replybar").hidden=true;const mq=query(collection(db,"chats",c.id,"messages"),orderBy("createdAt","desc"),limit(100));const unsub=onSnapshot(mq,snap=>{state.messages=snap.docs.map(d=>({id:d.id,...d.data()})).reverse();renderMessages();markVisibleRead()},e=>toast("Messages unavailable: "+errText(e)));state.unsubs.push(unsub);const tu=onSnapshot(collection(db,"chats",c.id,"typing"),s=>{$("typing").hidden=!s.docs.some(d=>d.id!==state.user.uid&&d.data().until?.toMillis?.()>Date.now())},()=>{});state.unsubs.push(tu)}
function renderMessages(){const box=$("messages"),needle=state.chatSearch.toLowerCase(),near=box.scrollHeight-box.scrollTop-box.clientHeight<120;box.innerHTML="";const arr=state.messages.filter(m=>(m.text||m.fileName||"").toLowerCase().includes(needle));if(!arr.length){box.innerHTML='<div class="empty-card" style="margin:auto;text-align:center"><p>No messages yet. Say hello 👋</p></div>';return}arr.forEach(m=>{const mine=m.senderId===state.user.uid,d=document.createElement("div");d.className="bubble"+(mine?" mine":"")+(m.deleted?" deleted":"");if(state.active?.isGroup&&!mine){const s=document.createElement("div");s.className="sender";s.textContent=state.active.memberNames?.[m.senderId]||m.senderName||"Member";d.append(s)}if(m.replyTo){const r=document.createElement("div");r.className="reply";r.textContent="Reply: "+(m.replyTo.text||"");d.append(r)}if(m.deleted)d.append(Object.assign(document.createElement("span"),{textContent:"This message was deleted."}));else{if(m.imageUrl){const im=document.createElement("img");im.src=m.imageUrl;im.alt=m.fileName||"Image";im.onclick=()=>window.open(m.imageUrl,"_blank","noopener");d.append(im)}if(m.fileUrl&&!m.imageUrl){const a=document.createElement("a");a.className="file-link";a.href=m.fileUrl;a.target="_blank";a.rel="noopener";a.textContent="📎 "+(m.fileName||"Open file");d.append(a)}if(m.text){const s=document.createElement("div");s.className="bubble-text";s.textContent=m.text;d.append(s)}}if(m.reaction){const r=document.createElement("span");r.className="reaction";r.textContent=m.reaction;d.append(r)}const meta=document.createElement("div");meta.className="meta";const ts=m.createdAt?.toDate?m.createdAt.toDate().toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"}):"Sending";meta.textContent=ts+(m.edited?" · edited":"")+(mine?(Object.keys(m.readBy||{}).some(k=>k!==state.user.uid)?" · ✓✓":" · ✓"):"");d.append(meta);if(!m.deleted){const tools=document.createElement("div");tools.className="bubble-tools";tools.append(mkBtn("↩",()=>setReply(m)),mkBtn("☺",()=>react(m)),mkBtn("Copy",()=>navigator.clipboard?.writeText(m.text||"")));if(mine)tools.append(mkBtn("Edit",()=>edit(m)),mkBtn("Delete",()=>del(m)));d.append(tools)}box.append(d)});if(near)box.scrollTop=box.scrollHeight}
function mkBtn(t,fn){const b=document.createElement("button");b.type="button";b.textContent=t;b.onclick=fn;return b}
function setReply(m){state.reply={id:m.id,text:m.text||""};$("replyText").textContent="Replying: "+(m.text||m.fileName||"").slice(0,100);$("replybar").hidden=false;$("messageInput").focus()}
async function edit(m){const v=prompt("Edit message",m.text||"");if(v===null||!v.trim())return;try{await updateDoc(doc(db,"chats",state.active.id,"messages",m.id),{text:v.trim(),edited:true})}catch(e){toast(errText(e))}}
async function del(m){if(!confirm("Delete this message for everyone?"))return;try{await updateDoc(doc(db,"chats",state.active.id,"messages",m.id),{text:"",deleted:true})}catch(e){toast(errText(e))}}
async function react(m){const choices=["❤️","👍","😂","😮","😢","🔥"],next=choices[(choices.indexOf(m.reaction)+1)%choices.length];try{await updateDoc(doc(db,"chats",state.active.id,"messages",m.id),{reaction:next})}catch(e){toast(errText(e))}}
async function sendMessage(){const input=$("messageInput"),text=input.value.trim();if(!text||!state.active)return;input.value="";updateCount();setTyping(false);try{const data={senderId:state.user.uid,text,createdAt:serverTimestamp(),readBy:{[state.user.uid]:serverTimestamp()}};if(state.reply)data.replyTo={id:state.reply.id,text:state.reply.text.slice(0,200)};await addDoc(collection(db,"chats",state.active.id,"messages"),data);await updateDoc(doc(db,"chats",state.active.id),{lastActivityAt:serverTimestamp(),lastMessage:text.slice(0,120)});state.reply=null;$("replybar").hidden=true}catch(e){input.value=text;toast("Message not sent: "+errText(e))}}
async function sendFile(file){if(!file||!state.active)return;if(file.size>15*1024*1024)return toast("Maximum file size is 15 MB.");const ok=file.type.startsWith("image/")||["application/pdf","text/plain","application/zip","application/msword","application/vnd.openxmlformats-officedocument.wordprocessingml.document"].includes(file.type);if(!ok)return toast("This file type is not supported.");try{const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,"_"),r=ref(storage,"chatFiles/"+state.active.id+"/"+state.user.uid+"/"+Date.now()+"_"+safe);await uploadBytes(r,file);const url=await getDownloadURL(r),data={senderId:state.user.uid,createdAt:serverTimestamp(),readBy:{[state.user.uid]:serverTimestamp()},fileUrl:url,fileName:file.name,fileType:file.type};if(file.type.startsWith("image/"))data.imageUrl=url;await addDoc(collection(db,"chats",state.active.id,"messages"),data);await updateDoc(doc(db,"chats",state.active.id),{lastActivityAt:serverTimestamp(),lastMessage:"📎 "+file.name.slice(0,100)});toast("File sent.")}catch(e){toast("Upload failed: "+errText(e))}}
async function markVisibleRead(){if(!state.active)return;const latest=state.messages.slice(-20).filter(m=>m.senderId!==state.user.uid&&!m.readBy?.[state.user.uid]);for(const m of latest){try{await updateDoc(doc(db,"chats",state.active.id,"messages",m.id),{["readBy."+state.user.uid]:serverTimestamp()})}catch{}}}
async function setTyping(on){if(!state.active)return;clearTimeout(typingTimeout);const r=doc(db,"chats",state.active.id,"typing",state.user.uid);try{if(on){await setDoc(r,{until:new Date(Date.now()+3500)});typingTimeout=setTimeout(()=>setTyping(false),2500)}else await setDoc(r,{until:new Date(0)})}catch{}}
async function addMember(){if(!state.active?.isGroup||state.active.createdBy!==state.user.uid)return;const u=(prompt("Username to add")||"").trim().toLowerCase();if(!/^[a-z0-9_]{3,20}$/.test(u))return;try{const qs=await getDocs(query(collection(db,"users"),where("username","==",u),limit(1)));if(qs.empty)return toast("User not found.");const uid=qs.docs[0].id;if((state.active.members||[]).includes(uid))return toast("Already a member.");await updateDoc(doc(db,"chats",state.active.id),{members:arrayUnion(uid)});state.active.members=[...(state.active.members||[]),uid];toast("Member added.")}catch(e){toast(errText(e))}}
function invite(){if(!state.active?.isGroup)return;const url=location.href.split("?")[0]+"?join="+encodeURIComponent(state.active.id);navigator.clipboard?.writeText(url).then(()=>toast("Invite link copied."),()=>prompt("Copy invite link",url))}
async function handleJoin(){const id=new URLSearchParams(location.search).get("join");if(!id||!state.user)return;try{const s=await getDoc(doc(db,"chats",id));if(!s.exists()||!s.data().isGroup)return;await updateDoc(doc(db,"chats",id),{members:arrayUnion(state.user.uid)});history.replaceState({}, "", location.pathname);toast("Joined group.");startHomeListener()}catch(e){toast("Could not join group: "+errText(e))}}
function updateCount(){$("count").textContent=$("messageInput").value.length+" / 2000"}
function applyTheme(){document.body.classList.toggle("dark",state.theme==="dark");$("themeBtn").textContent=state.theme==="dark"?"☀":"◐";localStorage.setItem("qavli-theme",state.theme)}
function profileEdit(){openModal("profileModal");$("profileName").value=state.profile.displayName||"";const av=$("profileAvatar");av.innerHTML=state.profile.avatarUrl?'<img src="'+state.profile.avatarUrl.replace(/"/g,"&quot;")+'" alt="">':initials(state.profile.displayName)}
async function saveProfileChanges(){const n=$("profileName").value.trim();if(!n||n.length>40)return $("profileEditError").textContent="Enter a display name up to 40 characters.";try{await updateDoc(doc(db,"users",state.user.uid),{displayName:n});state.profile.displayName=n;await updateProfile(state.user,{displayName:n});closeModal();renderChats();toast("Profile updated.")}catch(e){$("profileEditError").textContent=errText(e)}}
async function uploadAvatar(file){if(!file||!file.type.startsWith("image/"))return toast("Choose an image.");if(file.size>5*1024*1024)return toast("Maximum profile image size is 5 MB.");try{const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,"_"),r=ref(storage,"avatars/"+state.user.uid+"/"+Date.now()+"_"+safe);await uploadBytes(r,file);const url=await getDownloadURL(r);await updateDoc(doc(db,"users",state.user.uid),{avatarUrl:url});state.profile.avatarUrl=url;profileEdit();toast("Profile photo updated.");renderChats()}catch(e){toast("Photo upload failed: "+errText(e))}}

$("authForm").onsubmit=e=>{e.preventDefault();$("authForm").dataset.mode==="signup"?signUp():signIn()};
$("authSwitch").onclick=()=>showAuth($("authForm").dataset.mode==="signup"?"signin":"signup");$("forgot").onclick=resetPassword;$("saveProfile").onclick=saveProfile;$("newChatBtn").onclick=()=>openModal("newChatModal");$("groupBtn").onclick=()=>openModal("groupModal");$("newChatCreate").onclick=newChat;$("groupCreate").onclick=createGroup;$("closeNewChat").onclick=closeModal;$("closeGroup").onclick=closeModal;$("closeProfile").onclick=closeModal;$("saveProfileChanges").onclick=saveProfileChanges;$("profileBtn").onclick=profileEdit;$("signOut").onclick=()=>signOut(auth);$("themeBtn").onclick=()=>{state.theme=state.theme==="dark"?"light":"dark";applyTheme()};$("backBtn").onclick=closeChat;$("messageForm").onsubmit=e=>{e.preventDefault();sendMessage()};$("attachBtn").onclick=()=>$("fileInput").click();$("fileInput").onchange=e=>{sendFile(e.target.files[0]);e.target.value=""};$("messageInput").oninput=()=>{updateCount();setTyping(Boolean($("messageInput").value.trim()))};$("replyCancel").onclick=()=>{state.reply=null;$("replybar").hidden=true};$("chatSearchBtn").onclick=()=>{$("chatTools").classList.toggle("open");if($("chatTools").classList.contains("open"))$("chatSearch").focus()};$("chatSearch").oninput=e=>{state.chatSearch=e.target.value.toLowerCase();renderMessages()};$("manageBtn").onclick=addMember;$("inviteBtn").onclick=invite;$("profileFile").onchange=e=>uploadAvatar(e.target.files[0]);$("chatSearchHome").oninput=e=>{state.search=e.target.value;renderChats()};$("closeFatal").onclick=()=>location.reload();document.querySelectorAll(".modal-backdrop").forEach(m=>m.addEventListener("click",e=>{if(e.target===m)closeModal()}));
window.addEventListener("online",()=>{if(state.user)toast("Back online.")});window.addEventListener("offline",()=>toast("You are offline."));
applyTheme();
(async()=>{try{await setPersistence(auth,browserLocalPersistence);onAuthStateChanged(auth,async user=>{if(user){setBusy($("authAction"),false);await finishAuth(user);await handleJoin()}else{state.user=null;state.profile=null;clearAllListeners();showAuth("signin")}})}catch(e){showFatal("Firebase could not start. "+errText(e))}})();
