plugins {
    id 'com.android.application'
}

android {
    namespace 'com.qavli.chat'
    compileSdk 35

    defaultConfig {
        applicationId 'com.qavli.chat'
        minSdk 23
        targetSdk 35
        versionCode (System.getenv('GITHUB_RUN_NUMBER') ?: '1').toInteger()
        versionName "1.0.${System.getenv('GITHUB_RUN_NUMBER') ?: '1'}"
    }
}
